# 文件名: environment.yml

name: pc2mesh-env
channels:
  - conda-forge
dependencies:
  # --- C++ 核心库 ---
  - cmake=3.27
  - make
  - gcc_linux-64=12
  - gxx_linux-64=12
  - pkg-config
  - boost=1.82
  - eigen=3.4
  - cgal=5.6
  - openvdb=10.0
  - tbb-devel
  # - libigl      # <--- 删除或注释掉这一行
  - pcl=1.13.1  # <--- 保留这个关键的版本
  - nlohmann_json=3.11.2
  - yaml-cpp=0.7.0
  - opencv

  # --- Python 依赖 ---
  - python=3.11
  - pip
  - numpy
  - scipy
  - matplotlib
  - pyyaml
  - pybind11

  # --- Pip 安装部分 ---
  - pip:
    - pyvista
    - plotly